<package>
  <name>panda_spherized_description</name>
  <version>0.8.3</version>
  <description>Spherized panda model used for MoveIt! testing</description>

  <author email="philiphuang@cmu.edu">Philip Huang</author>

  <maintainer email="philiphuang@cmu.edu">Philip Huang</maintainer>

  <license>BSD</license>
  <url type="website">http://moveit.ros.org</url>
  <url type="bugtracker">https://github.com/ros-planning/moveit-resources/issues</url>
  <url type="repository">https://github.com/ros-planning/moveit-resources</url>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>xacro</build_depend>
</package>