# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - panda_multi_arm_controller

  panda_multi_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - panda0_joint1
      - panda0_joint2
      - panda0_joint3
      - panda0_joint4
      - panda0_joint5
      - panda0_joint6
      - panda0_joint7
      - panda1_joint1
      - panda1_joint2
      - panda1_joint3
      - panda1_joint4
      - panda1_joint5
      - panda1_joint6
      - panda1_joint7
      - panda2_joint1
      - panda2_joint2
      - panda2_joint3
      - panda2_joint4
      - panda2_joint5
      - panda2_joint6
      - panda2_joint7
      - panda3_joint1
      - panda3_joint2
      - panda3_joint3
      - panda3_joint4
      - panda3_joint5
      - panda3_joint6
      - panda3_joint7
      - panda4_joint1
      - panda4_joint2
      - panda4_joint3
      - panda4_joint4
      - panda4_joint5
      - panda4_joint6
      - panda4_joint7
      - panda5_joint1
      - panda5_joint2
      - panda5_joint3
      - panda5_joint4
      - panda5_joint5
      - panda5_joint6
      - panda5_joint7
    action_ns: follow_joint_trajectory
    default: true