# Default initial positions for panda's ros2_control fake system

initial_positions:
  panda0_finger_joint1: 0
  panda0_joint1: 0
  panda0_joint2: 0
  panda0_joint3: 0
  panda0_joint4: 0
  panda0_joint5: 0
  panda0_joint6: 0
  panda0_joint7: 0
  panda1_finger_joint1: 0
  panda1_joint1: 0
  panda1_joint2: 0
  panda1_joint3: 0
  panda1_joint4: 0
  panda1_joint5: 0
  panda1_joint6: 0
  panda1_joint7: 0
  panda2_finger_joint1: 0
  panda2_joint1: 0
  panda2_joint2: 0
  panda2_joint3: 0
  panda2_joint4: 0
  panda2_joint5: 0
  panda2_joint6: 0
  panda2_joint7: 0
  panda3_finger_joint1: 0
  panda3_joint1: 0
  panda3_joint2: 0
  panda3_joint3: 0
  panda3_joint4: 0
  panda3_joint5: 0
  panda3_joint6: 0
  panda3_joint7: 0
  panda4_finger_joint1: 0
  panda4_joint1: 0
  panda4_joint2: 0
  panda4_joint3: 0
  panda4_joint4: 0
  panda4_joint5: 0
  panda4_joint6: 0
  panda4_joint7: 0
  panda5_finger_joint1: 0
  panda5_joint1: 0
  panda5_joint2: 0
  panda5_joint3: 0
  panda5_joint4: 0
  panda5_joint5: 0
  panda5_joint6: 0
  panda5_joint7: 0
  panda6_finger_joint1: 0
  panda6_joint1: 0
  panda6_joint2: 0
  panda6_joint3: 0
  panda6_joint4: 0
  panda6_joint5: 0
  panda6_joint6: 0
  panda6_joint7: 0
  panda7_finger_joint1: 0
  panda7_joint1: 0
  panda7_joint2: 0
  panda7_joint3: 0
  panda7_joint4: 0
  panda7_joint5: 0
  panda7_joint6: 0
  panda7_joint7: 0